const menWear = [
    {
      _id: '1',
      wearType: 'Top Wear',
      item: 'T-Shirts',
      name:'U.S. Polo Assn',
      brand:'nike',
      pic:'U.S. Polo Assn.jpg',
      size:['M', 'L', 'XL', 'XXL'],
      color:['red','yellow','white','blue','green'],
      rate: 1500,
      description:'Men Yellow Blue Striped Pure Cotton Polo Collar Pure Cotton T-shirt',
      quantity: 25,
      ratings:1,
      reviews:"This one also good & somehow I'm satisfied except the length is bit shorter than expected.",
      trend:'no',
      seasonFavorite:'yes',
      mostPurchased:6
    },

    {
        _id: '2',
        wearType: 'Top Wear',
        item: 'T-Shirts',
        name:'HRX by Hrithik Roshan',
        brand:'nike',
        pic:'HRX by Hrithik Roshan.jpg',
        size:['M', 'L', 'XL', 'XXL'],
        color:['red','yellow','white','blue','green'],
        rate: 1300,
        description:'Men Yellow Printed Cotton Pure Cotton T-shirt',
        quantity: 30,
        ratings: 1.5,
        reviews:"Nice one color is Same as shown in the product image, perfect fit and love this one",
        trend:'yes',
        seasonFavorite:'yes',
        mostPurchased:7
    },

    {
        _id: '3',
        wearType: 'Top Wear',
        item: 'T-Shirts',
        name:'Calvin Klein Jeans',
        brand:'nike',
        pic:'kelvin Clean.jpg',
        size:['M', 'L', 'XL', 'XXL'],
        color:['red','yellow','white','blue','green'],
        rate: 938,
        description:'Men Black Brand Logo Printed Slim Fit Pure Cotton T-shirt',
        quantity: 35,
        ratings:2,
        reviews:"This one also good & somehow I'm satisfied except the length is bit shorter than expected. Thanks freeQ",
        trend:'yes',
        seasonFavorite:'yes',
        mostPurchased:8
    },

    {
        _id: '4',
        wearType: 'Top Wear',
        item: 'T-Shirts',
        name:'Roadster',
        brand:'nike',
        pic:'Roadster.jpg',
        size:['M', 'L', 'XL', 'XXL'],
        color:['red','yellow','white','blue','green'],
        rate: 1100,
        description:'Men Red Black Pure Cotton Brand Logo Print Round Neck Pure Cotton T-shirt',
        quantity: 40,
        ratings:2.5,
        reviews:"It looks like a premium tshirt, Must buy guys. Thank you",
        trend:'yes',
        seasonFavorite:'yes',
        mostPurchased:9
    },

    {
        _id: '5',
        wearType: 'Top Wear',
        item: 'T-Shirts',
        name:'Nautica',
        brand:'nike',
        pic:'Nautica.jpg',
        size:['M', 'L', 'XL', 'XXL'],
        color:['red','yellow','white','blue','green'],
        rate: 3250,
        description:'Men Dark Blue Solid Polo Collar Regular Sleeves Pure Cotton T-shirt',
        quantity: 45,
        ratings:3,
        reviews:"Great product good quality I can always trust Myntra for great service and good customer response have always had a good experience.",
        trend:'no',
        seasonFavorite:'yes',
        mostPurchased:10
    },

    {
        _id: '6',
        wearType: 'Top Wear',
        item: 'T-Shirts',
        name:'Roadster Blk',
        brand:'nike',
        pic:'Roadster Blk.jpg',
        size:['M', 'L', 'XL', 'XXL'],
        color:['red','yellow','white','blue','green'],
        rate: 1275,
        description:'Men Black & White Typography Printed Pure Cotton T-shirt',
        quantity: 50,
        ratings:3.5,
        reviews:"Black and white Tshirt for men Typography printed Regular length Round neck.",
        trend:'yes',
        seasonFavorite:'yes',
        mostPurchased:11
    },

    {
        _id: '7',
        wearType: 'Top Wear',
        item: 'T-Shirts',
        name:'Puma Grant',
        brand:'Puma',
        pic:'puma.jpg',
        size:['M', 'L', 'XL', 'XXL'],
        color:['red','yellow','white','blue','green'],
        rate: 1900,
        description:'Men Orange Brand Logo Printed Round Neck T-shirt',
        quantity: 55,
        ratings:4,
        reviews:"The world cant wait, so lets take our forever faster approach and move forward on sustainability. ",
        trend:'no',
        seasonFavorite:'yes',
        mostPurchased:12
    },

    {
        _id: '8',
        wearType: 'Top Wear',
        item: 'T-Shirts',
        name:'Roadster life Go',
        brand:'Puma',
        pic:'Roadster life Go.jpg',
        size:['M', 'L', 'XL', 'XXL'],
        color:['red','yellow','white','blue','green'],
        rate: 2200,
        description:'Men Teal Green Solid Round Neck T-shirt',
        quantity: 40,
        ratings:4.5,
        reviews:"It looks perfect i ordered m size though my ht is 5 11 , colour looks beautiful simple and material ised is great ",
        trend:'no',
        seasonFavorite:'yes',
        mostPurchased:13
    },
  ]
  
  export default menWear
  